/*
 * Animated GIF, written here, for the same reason the PNG codec is written here.
 *
 * The point of --record is that the demo in the README can be regenerated by
 * anyone who clones the repository, with one command and no tools they have to
 * install first. That rules out shelling out to anything, so: a global colour
 * table built from the frames themselves, and LZW.
 */

#ifndef GIF_H
#define GIF_H

#include <stddef.h>
#include <stdint.h>

#include "png.h"

typedef enum { GIF_OK = 0, GIF_ERR_ARGUMENT, GIF_ERR_MEMORY, GIF_ERR_IO } gif_status_t;

typedef struct gif_writer gif_writer_t;

/*
 * delay_hundredths is what the viewer waits between frames. The palette is built
 * from the first frame handed over, which for this program is representative:
 * the background and the ramp are the whole image.
 */
gif_status_t gif_open(gif_writer_t **writer, const char *path, int width, int height,
                      int delay_hundredths);

/* Colours the table must have whatever the first frame shows. The table is built
 * from the first frame, and a colour that only comes into view later — a hawk that
 * has not flown on yet — would be drawn in the nearest colour the table has, which
 * is a red as a grey. At most GIF_MAX_RESERVED, before the first frame. */
enum { GIF_MAX_RESERVED = 32 };
gif_status_t gif_reserve_colours(gif_writer_t *writer, const uint8_t (*rgb)[3], int count);

/* RGBA in, alpha ignored: a GIF frame is opaque. */
gif_status_t gif_add_frame(gif_writer_t *writer, const png_image_t *frame);

/* Writes the trailer and closes. Safe on a writer that failed along the way. */
gif_status_t gif_close(gif_writer_t *writer, size_t *bytes_written, int *frames_written);

const char *gif_status_string(gif_status_t status);

#endif
