/*
 * Animated GIF, written here, for the same reason the PNG codec is written here.
 *
 * The point of --record is that the demo in the README can be regenerated by
 * anyone who clones the repository, with one command and no tools they have to
 * install first. That rules out shelling out to anything, so: a global colour
 * table built from the frames themselves, and LZW.
 */

#ifndef GIF_H
#define GIF_H

#include <stddef.h>
#include <stdint.h>

#include "png.h"

typedef enum { GIF_OK = 0, GIF_ERR_ARGUMENT, GIF_ERR_MEMORY, GIF_ERR_IO } gif_status_t;

typedef struct gif_writer gif_writer_t;

/*
 * delay_hundredths is what the viewer waits between frames. The palette is built
 * from the first frame handed over, which for this program is representative:
 * the background and the ramp are the whole image.
 */
gif_status_t gif_open(gif_writer_t **writer, const char *path, int width, int height,
                      int delay_hundredths);

/*
 * Colours that are not in the first frame and will be in later ones. The palette
 * is made from the first frame alone, so a colour that only turns up afterwards is
 * drawn in the nearest one that has an entry, and the one thing a clip was made to
 * show comes out grey: a gold light that runs through a flock, or the colours a
 * text flies in after it has rested as the command's output. A reserved colour
 * takes an entry before anything is counted, exactly as given, in the order
 * given, and whatever else falls in its bucket is drawn in it, a bucket being too
 * small for anyone to tell. Colours that share a bucket share an entry, which is
 * their mean. Calls add to the list, up to GIF_RESERVED_MAX in all, and only
 * before the first frame; with none reserved the palette is exactly what the
 * first frame makes. A call that cannot be kept whole is refused and changes
 * nothing.
 */
enum { GIF_RESERVED_MAX = 32 };
gif_status_t gif_reserve_colours(gif_writer_t *writer, const uint8_t (*colours)[3], int count);

/* RGBA in, alpha ignored: a GIF frame is opaque. */
gif_status_t gif_add_frame(gif_writer_t *writer, const png_image_t *frame);

/* Writes the trailer and closes. Safe on a writer that failed along the way. */
gif_status_t gif_close(gif_writer_t *writer, size_t *bytes_written, int *frames_written);

const char *gif_status_string(gif_status_t status);

#endif
