/*
 * Turns a PNG file into the C header that is compiled into cbirds.
 *
 * The file is validated with our own decoder before being emitted, so a
 * broken or unsupported image is caught here instead of at runtime.
 *
 *     make asset          regenerates sprite_png.h from resources/matrix.png
 */

#include <stdio.h>
#include <stdlib.h>

#include "../png.h"

#define BYTES_PER_LINE 16

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "Usage: %s <input.png> <output.h> <symbol>\n", argv[0]);
        return EXIT_FAILURE;
    }
    const char *in_path = argv[1], *out_path = argv[2], *symbol = argv[3];

    FILE *in = fopen(in_path, "rb");
    if (in == NULL) {
        perror(in_path);
        return EXIT_FAILURE;
    }
    if (fseek(in, 0, SEEK_END) < 0) {
        perror(in_path);
        fclose(in);
        return EXIT_FAILURE;
    }
    long size = ftell(in);
    rewind(in);
    if (size <= 0) {
        fprintf(stderr, "%s: empty file\n", in_path);
        fclose(in);
        return EXIT_FAILURE;
    }

    uint8_t *data = (uint8_t *)malloc((size_t)size);
    if (data == NULL || fread(data, 1, (size_t)size, in) != (size_t)size) {
        fprintf(stderr, "%s: cannot read the file\n", in_path);
        free(data);
        fclose(in);
        return EXIT_FAILURE;
    }
    fclose(in);

    png_image_t image = {0, 0, NULL};
    png_status_t status = png_decode(data, (size_t)size, &image);
    if (status != PNG_OK) {
        fprintf(stderr, "%s: %s\n", in_path, png_status_string(status));
        free(data);
        return EXIT_FAILURE;
    }
    printf("%s : %dx%d, %ld bytes\n", in_path, image.width, image.height, size);
    png_image_free(&image);

    FILE *out = fopen(out_path, "wb");
    if (out == NULL) {
        perror(out_path);
        free(data);
        return EXIT_FAILURE;
    }
    fprintf(out,
            "/* Generated by tools/mkasset from %s : do not edit.\n"
            " * Regenerate with `make asset`. */\n\n"
            "#ifndef SPRITE_PNG_H\n#define SPRITE_PNG_H\n\n"
            "#include <stddef.h>\n#include <stdint.h>\n\n"
            "static const uint8_t %s[] = {",
            in_path, symbol);
    for (long i = 0; i < size; i++) {
        fprintf(out, "%s0x%02x,", i % BYTES_PER_LINE == 0 ? "\n    " : " ", data[i]);
    }
    fprintf(out, "\n};\n\nstatic const size_t %s_len = sizeof(%s);\n\n#endif\n", symbol, symbol);
    fclose(out);
    free(data);
    printf("%s written\n", out_path);
    return EXIT_SUCCESS;
}
